/*
 * GameTanView.java
 */

package gametan;

import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

/**
 * The application's main frame.
 */
public class GameTanView extends FrameView {
    
    public GameTanView(SingleFrameApplication app) {
        super(app);
        
        initComponents();
        getFrame().setResizable(false);
        setComponent(pnSession);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private jPanelSession pnSession = new jPanelSession();
    
}
